server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:h2:mem:library'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
  h2:
    console:
      enabled: true
      path: '/h2-console'